### ISSUE TITLE
Unable to use Cs50 library in my Linux terminal

### ISSUE THREAD

**Issue by dextercva** [cs50/libcs50#157]
**what is the solution for below mentioned problem**

My code,
`#include <cs50.h>`
`#include <stdio.h>`

`int main(void)`
`{`
  `  // Prompt user for answer`
    `char c = get_char("Answer: ");`
`
    // Check answer`
   ` if (c == 'Y' || c == 'y')`
   ` {`
       ` printf("yes\n");`
    `}`
    `else if (c == 'N' || c == 'n')`
   ` {`
       ` printf("no\n");`
  `  }`
`}`

Then i ran 

`clang -o answer answer.c -lcs50`
`answer.c:3:10: fatal error: 'cs50.h' file
      not found
#include <cs50.h>
         ^~~~~~~~
1 error generated.`
Also i ran make,
`make answer`
`cc     answer.c   -o answer`
`answer.c:3:10: fatal error: 'cs50.h' file
      not found
#include <cs50.h>
         ^~~~~~~~
1 error generated.
make: *** [<builtin>: answer] Error 1`

**Comment by dmalan** [comment]
Have you installed the library per https://github.com/cs50/libcs50/blob/develop/README.md? If so, if you re-do the appropriate steps, what is the output?

**Comment by dextercva** [comment]
_I forget to mention that I'm using Linux terminal in termux application which is android application._

As per link provided i had downloaded the libcs50-9.0.0, then i typed
`make install`
It's showing that unable to create sub directories because I'm not sudo user

Next,
So what i did was, i copied `cs50.h` file in `usr/include/` by doing this now it's not saying cs50.h not found means somehow compiler locates cs50.h

Then i ran 
`make answer `
It has shown this error.
` cc     answer.c   -o answer                  `             
` /data/data/com.termux/files/usr/bin/aarch64-linux-android-ld: `
`/data/data/com.termux/files/usr/tmp/answer-72eb22.o: in function main':                                           answer.c:(.text+0x3c): undefined reference to get_char'  `
` clang-7: error: linker command failed with exit code 1 (use -v to see invocation)                                     make: *** [<builtin>: answer] Error 1`

Also i tried to copy shared object `libcs50.so  libcs50.so.9.0.0`  files to `usr/lib` they aren't either copying or moving.

**Comment by kzidane** [comment]
@dextercva usually you need to be `root` to install something in `/usr/*`, so `sudo make install` should work. Alternatively, you could install somewhere else that doesn't require `root` access by setting `DESTDIR` (e.g., `DESTDIR=my/new/path make install`. Also be sure to link the CS50 library using `-lcs50` in your compilation command. If your library files aren't installed in standard locations, you may need to pass `-I` for includes path and `-L` for shared object path too. See your compiler's manual for more information!

**Comment by Sebbyastian** [comment]
This is the problem with relying upon some non-standard library to teach C... and then expecting `sudo` to exist on Android (have you ever used Android before?)...

Remove: `#include <cs50.h>`

Insert: `if (fread(&c, 1, 1, stdin) != 1) { puts("error"); }` before `if (c == 'Y' || c == 'y')`

Change:

- `char c = /* gibberish here */;` to `char c;`
- `if (c == 'Y' || c == 'y')` to `else if (c == 'Y' || c == 'y')`

At this point you'll have something that closely replicates the behaviour of the program you specified, in vanilla C. You might need some Android development key to sign the binary in order to execute it. I'm not so familiar with Android development, but last time I tried to run an unsigned application I had problems...

**Comment by shrek56** [comment]
I forget to mention that I'm using Linux terminal in termux application which is android application.

As per link provided i had downloaded the libcs50-9.0.0, then i typed
make install
It's showing that unable to create sub directories because I'm not sudo user

Next,
So what i did was, i copied cs50.h file in usr/include/ by doing this now it's not saying cs50.h not found means somehow compiler locates cs50.h

Then i ran
make answer
It has shown this error.
cc answer.c -o answer
/data/data/com.termux/files/usr/bin/aarch64-linux-android-ld:
/data/data/com.termux/files/usr/tmp/answer-72eb22.o: in function main': answer.c:(.text+0x3c): undefined reference to get_char'
clang-7: error: linker command failed with exit code 1 (use -v to see invocation) make: *** [<builtin>: answer] Error 1

also i have a installed libcs50 and then moved it to /usr/include     however it was also displaying error so i again copies all files to /usr/bin but still it's not working
