### ISSUE TITLE
cs50.h defines type string to be a pointer to a string

### ISSUE THREAD

**Issue by rillig** [cs50/libcs50#163]
The file `cs50.h` defines the type `string` as follows:

    typedef char *string;

The C standard says in 7.1.1p1:

> A _string_ is a contiguous sequence of characters terminated by and including the first null character.
> […]
> A _pointer to a string_ is a pointer to its initial (lowest addressed) character.

What this header calls a string is actually a pointer to a string. This can lead to confusion. Especially in teaching, confusion should be avoided as far as possible.

To clarify this situation, the documenting comment should at least explain the reason why this type definition is necessary and useful, and what a string really is.

**Comment by dmalan** [comment]
Thanks for the citation, though this one I think we'll largely leave as is, though I've added a parenthetical to our comments. As defined, I do think `string` is a reasonable (and, daresay, commonly accepted) abstraction for a sequence of characters that just so happens to be represented underneath the hood as the address of a `char`. Indeed, even the man pages for libc use the terms interchangeably.

**Comment by Sebbyastian** [comment]
This is an example of why I wrote on your subreddit that your lessons teach a poor understanding of the languages... I hope rillig will stop trying to help you, as I've decided, and instead focus on helping those you mislead.

> daresay, commonly accepted

... by people who don't know C. This is a good excuse when you want those who actually know C to start mocking you. I wonder if you'd rather be oblivious to the mocking?

The address of a `char` is not necessarily _a contiguous sequence of characters terminated by and including the first null character_, hence you are actually seeding confusion.

> that just so happens to be represented underneath the hood as the address of a `char`

... not to mention [`wchar_t`](http://pubs.opengroup.org/onlinepubs/9699919799/functions/wcslen.html), `char16_t` and `char32_t`... no, the only people on this planet are English-speakers, with 8-bit `char` types...

... and heaven forbid should you write a sequence of characters that terminates at the first '\0' (including the '\0') to a file (i.e. `fwrite(fd, strlen(str) + 1, 1, str);`)... what's the _address_ for that _string_? Or is that not a _string_ anymore? See, this is where the confusion arises. Either `char *` is synonymous with "string" (_it isn't_), and you don't have words to describe the actual representation... or you have a _proper_ understanding.

> Indeed, even the man pages for libc use the terms interchangeably.

[OpenGroup](https://pubs.opengroup.org/onlinepubs/9699919799/functions/strlen.html) (and a version of [Arch Linux](https://jlk.fjfi.cvut.cz/arch/manpages/man/core/man-pages/strlen.3p.en) says:

> The strlen() function shall compute the number of bytes in the string to which s points, not including the terminating NUL character.

OpenGroup decides what constitutes POSIX C, which is most likely what you want to try to fit your lessons into...

[man7](http://man7.org/linux/man-pages/man3/strlen.3.html) (and [Arch](https://jlk.fjfi.cvut.cz/arch/manpages/man/core/man-pages/strlen.3.en), [Debian](https://manpages.debian.org/stretch/manpages-dev/strlen.3.en.html)) says:

> The strlen() function calculates the length of the string pointed to by s, excluding the terminating null byte ('\0').

You might find this kind of language clearer.

I think you're probably using an old Ubuntu Linux installation, or something else that isn't quite POSIX compliant, for your documentation... even Ubuntu is starting to pick up on this mistake, though to be clear they've had POSIX-compliant manuals for years now ([1](https://manpages.ubuntu.com/manpages/precise/en/man3/strlen.3posix.html), [2](https://manpages.ubuntu.com/manpages/trusty/en/man3/strlen.3posix.html), [3](https://manpages.ubuntu.com/manpages/xenial/en/man3/strlen.3posix.html), [4](https://manpages.ubuntu.com/manpages/bionic/en/man3/strlen.3posix.html), [6](https://manpages.ubuntu.com/manpages/cosmic/en/man3/strlen.3posix.html), [7](https://manpages.ubuntu.com/manpages/disco/en/man3/strlen.3posix.html))... from this line of research it seems to me like in the latter versions of Ubuntu they've patched all their documentation ([1](https://manpages.ubuntu.com/manpages/bionic/en/man3/strlen.3.html), [2](https://manpages.ubuntu.com/manpages/disco/en/man3/strlen.3.html), [3](https://manpages.ubuntu.com/manpages/cosmic/en/man3/strlen.3.html)); you should start to see the _correct_ language in your manpages starting with 18.04. It'd be a shame if everyone else moved on from this mistake, except for you... a shame for you and your students.

**Comment by rillig** [comment]
@Sebbyastian I totally agree. I only don't understand why I should only repair the damage done by these ignorant teachers, instead of fixing the knowledge of the teachers. The latter is a one-time operation, and I think it is more effective that correcting 1000 Stack Overflow users each year, who wrongly trusted their teachers. O(1) versus O(fib(years passed by)). :)

**Comment by Sebbyastian** [comment]
@rillig In that case, it would make more sense to start persuading universities to hire professors who [actually know C](https://github.com/cs50/libcs50/issues/151) to teach C (or hey, here's a better idea, just convince them to back away from C)... this way you turn an operation that occupies `O(n)` in time **and** space into an `O(n)` operation that occupies only space, right? That is, assuming the operation that is _persuasion_ is O(1) in time (that's a whole other problem which we need to deal with as a society).

**Comment by Sebbyastian** [comment]
Hell, he could teach C++ instead. There are [introductory books written for C++](https://stackoverflow.com/questions/388242/the-definitive-c-book-guide-and-list), by the founding forefather at that... where-as no such textbooks exist for C. This ought to be a big hint... C is not particularly introductory-friendly.

`typedef char *string` only pushes the issue of serialisation and deserialisation of files into the realm of _confusing as hell_. Most of your students won't bother to look deep into the library. I should hope you've accommodated for this in your lesson plans, but then again, I stopped auditing your lessons because **they're full of platform-specific nonsense** like the `sizeof` an `int` (which you've previously acknowledged but refused to fix, because you don't want to make your programming lessons about a specific platform... lol).

**Comment by ztane** [comment]
@Sebbyastian krhm... the bible of C language before standardization was "The C programming language" by K&R, an introductory book, where R *was* the founding forefather of the language; this predated the invention of C++, let alone any introductory books. Unfortunately R passed away 8 years ago so he's not here to defend his language against your attacks.

**Comment by JoelKatz** [comment]
I have seen this particular typedef confuse beginners more than once. The important thing to know is that this is a pointer and calling it a "string" confuses people. They expect its value to be the value of a string because it's called "string" and it's not. The only thing this does is hide that the type is a pointer and in order to use it, you must know that it's a pointer.

It does not help in any way. It doesn't save space or typing, "string" is actually longer than "char*". And in order to use it or tell if it's being used correctly, you have to know it's a pointer. So it doesn't hide any information that isn't always needed. Every C programmer must know what "char*" is or they can't understand this "typedef", so it doesn't avoid having to know or understand anything.

It literally serves no useful purpose whatsoever and does affirmative harm. What is the argument for keeping it?

**Comment by FreeER** [comment]
Ya'll act as if this isn't revealed by the end of the course, it's shown by week 2 with caesar cipher and others. What it does is allow you to get user input in week 1 without having to explain why there are multiplication symbols in the code when you're dealing with text not math or why you have to use pointers and what the difference from an array etc are. All of that does of course get covered but it doesn't need to be covered immediately and this lets them hide it for just the barest amount of introduction period. Nor is it particularly expect to be a library a bunch of people use and start typing `string` instead of `char*`. Remember, the most efficient way to program is not necessarily the most efficient way to teach/learn.
disclaimer: I'm just a random person who took CS50 a few years back on edx and enjoyed it once I got over trying to do everything on my own with just the lectures.

**Comment by JoelKatz** [comment]
@FreeER It's because we see the harm it does over and over. It may well be working for them, but it's producing students who don't understand why the value of something they called a "string" isn't a string. I haven't taken the CS50 course, but the evidence I've seen suggests that students do not come out of the course understanding that this is bad practice. At a minimum, there needs to be a big fat warnings because students can't be expected to figure this out on their own and experience says that they don't.

This particular pedagogical technique is doing harm to students.

**Comment by FreeER** [comment]
So you've see the harm it's done to CS50 students when it's explained in a week or students who picked it up from elsewhere and may never have had it explained?

**Comment by JoelKatz** [comment]
@FreeER People are only beginners for a very short time and you would be surprised how much of an impression the way they first learned things makes. It is perfectly fine to make things simpler for beginners, but making them confusing is a huge mistake. The main thing you need to know about this thing in order to use it is that it has the semantics of a pointer. You shouldn't teach beginners things they need to unlearn.

**Comment by FreeER** [comment]
Confusing them is inevitable. They aren't computers who are intuitively going to understand computers and the languages and tools invented to work with them even with explanations, they are going to get confused about things. At that point it's a question of do you ever simplify things, because if you do then the very fact hat you are simplifying something means you aren't teaching everything and they are going to have to unlearn the simplified teaching at some point to learn the more complete and correct teaching. You can argue that some things can be simplified without being wrong and you can just add to it, but the fact is that they have to learn that the simplified version isn't the full story and have to relearn the extra stuff so I don't seem it as being significantly different. And at that point it's just a matter of teaching style, perhaps worth teachers arguing over which is more effective, throwing everything at students or simplifying, but not a matter of the code itself and so doesn't belong here.

**Comment by JoelKatz** [comment]
@FreeER "not a matter of the code itself and so doesn't belong here"

I don't agree. I can understand the logic that it's the fault of those who teach badly that this confusion keeps occurring again and again. But that is just wrong. It **is** the code's fault. Code that leads people down a path that is known by experts to cause problems without adequate (or any) warning is just bad code. And once you see the harm it does, the sensible thing is to fix it.

Sure, you could educate every teacher so that they educate every student. Or, you could change the code once so that it doesn't set a trap for the unwary.

**Comment by rillig** [comment]
[Another harm done](https://codereview.stackexchange.com/a/242060/6499).

**Comment by Rubix982** [comment]
Can't we just switch over to C++ instead? It has a std::string which is exactly meant to treat this level of abstraction for people who are new and who might not be able to completely get how pointers work. std::string completely abstracts that - the people who want to understand how that works are invited to read the docs. 

`string` confused me as well when I started to work with cs50.h .  How all of the functions were working, which are just limited to cs50 itself, and why I can't use them anywhere else made me really confused when the errors threw words like `char *` which I didn't understand at the time.

**Comment by FreeER** [comment]
@Rubix982 https://www.quora.com/Why-does-CS50-at-Harvard-use-C-as-its-primary-language/answers/20631502

No matter what you pick and what abstractions you use there are going to be confusing issues, wtf is std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::basic_string<char*>(char*, char*, std::allocator<char> const&) for instance? what is std::cout, what is std, what is ::, why do we need using namespace std; etc. etc. Unlike typedef understanding what std::string really does is significantly more complicated (even if you leave out SSO).

Similarly programmers are very quickly going to run into third party libraries that have code that only works if you include that library... Even with C++ you can pretty quickly run into platform specific code like system("pause") system("cls") that's a similar problem with a potentially much more complicated solution since you can't just say, well include/link the library.

**Comment by Rubix982** [comment]
@FreeER, what you do suggest, then? 
It seems like the only was is to keep continue using C and remove `string` altogether. `char *` seems unavoidable as you say it.

**Comment by FreeER** [comment]
Exactly what CS50 originally chose to do, use a tiny abstraction of typedef char* string; which is removed in a week to reveal that it's a pointer. Nearly everyone that uses C refers to char*s as strings anyway so it's a good start there, including documentation and the standard library. Those who are really curious will spend their time breaking that abstraction early and those that aren't will have it broken soon enough regardless.

There's already help50 now to help with error messages as well as several CS50 focused communities along with all of the other more general C/programming ones and who knows how many tutorials and videos talking about pointers, strings, and allocating memory.

Though personally I wouldn't go so far as to add code to free them for educational purposes, allow it to leak and be one more thing for the curious to find and figure out. Though as a library to be used outside of the CS50 course I can't say it's a particularly bad thing... just closer to C++'s RAII/smart pointer concept than C's malloc/free one.
